apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeboard-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cafeboard-backend:latest # Jenkins에서 빌드할 이미지 명칭
        imagePullPolicy: IfNotPresent # 로컬 이미지를 우선 사용하도록 설정
        ports:
        - containerPort: 3001 # 5000에서 3001로 수정
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@cafeboard-db:5432/cafeboard?schema=public"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort # LoadBalancer에서 NodePort로 변경
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001 # 외부에서 3001로 접근
    targetPort: 3001 # 컨테이너 내부 3001로 전달
    nodePort: 30031 # 외부에서 접속할 고정 포트 30031 지정
