apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeboard-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cafeboard-frontend:latest # Jenkins에서 빌드할 이미지 명칭
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 # Nginx 기본 포트
        env:
        - name: VITE_API_URL # 프론트엔드에서 백엔드를 찾는 주소
          value: "http://localhost:5000" # 혹은 배포된 도메인
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # K3s의 ServiceLB를 사용하여 외부 노출
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80 # 브라우저에서 접속할 포트
    targetPort: 80
